stages:
  download_data:
    cmd: python ./src/features/data_downloading.py
    deps:
    - ./src/features/data_downloading.py
    outs:
    - ./data/raw/Dataset_FudanPed/PNGImages
    - ./data/raw/Dataset_FudanPed/PedMasks/
  preprocessing_data:
    cmd: python ./src/features/data_preprocessing.py
    deps:
    - ./src/features/data_preprocessing.py
    - ./data/raw/Dataset_FudanPed/PNGImages
    - ./data/raw/Dataset_FudanPed/PedMasks/    
    params:
    - preprocessing_data.seed
    - preprocessing_data.training_size
    - preprocessing_data.validation_size
    - preprocessing_data.testing_size
    outs:
    - ./data/processed/
