
[tool.coverage.run]
omit = ["src/models/data.py", "src/models/modelling.py", "src/models/segmentation_map.py", "src/features/built_features.py"]

[tool.pytest.ini_options]
testpaths = "tests"
addopts = "--junitxml=out/tests-report.xml --cov=src --cov-report=html:out/coverage" #path to the results file
